---
# Start here - prompt for Venafi credentials and a password for the privkey
- hosts: all
  become: false
  gather_facts: false
  collections: venafi.machine_identity
  vars_files: 
    - vars.yml
    - credentials.yml
  vars_prompt:
    - name: venafi_user
      prompt: "Venafi username"
      private: false
      default: <<VenServiceAccount>>
    - name: venafi_pwd
      prompt: "Venafi password"
      private: true
    - name: cert_pwd
      prompt: "Certificate password"
      private: true

  tasks:
    - assert:
        that: 
          - venafi_certs.subject_alt_names is iterable
          - venafi_certs.ip_addresses is iterable
        fail_msg: "IP addresses and/or subalt list not supplied"
        success_msg: "IP addresses and subalt lists OK"
    - include_tasks: format_san_list.yml
    - include_tasks: auth.yml
    - include_tasks: generate_certs.yml
    - include_tasks: revoke_access_token.yml
